### PR TITLE
CLapish_FirstScript.py

### PR DESCRIPTION
**Pull request by clapish**

### CODE REVIEW

**Comment by kevin-otto** [comment]
It appears that this pull request was redundant or vestigial. An updated pull request from clapish was merged.

**Comment by clapish** [comment]
This is Chloe Lapish, there are two Lapishes. The one you merged was Laurel's.

**Comment by kevin-otto** [comment]
Thank you Chloe. My mistake.

Your branch has a conflict. I believe the conflict is the fact that your file is named the same as Laurel's. Do you mind renaming your file please?

**Comment by clapish** [comment]
I changed the name to CLapish_FirstScript, so there should no longer be any conflicts.

**Pull request merged**
